### PR TITLE
Add `relate` tests

### PR DESCRIPTION
**Pull request by michaelkirk**
This PR adds support for the `relate` tests.

The sister PR which implements this functionality in `geo` is at https://github.com/georust/geo/pull/639

### CODE REVIEW

**Review by rmanoka — APPROVED** [review]
Looks great!  I didn't get to running the tests, but I assume all the tests are now passing.  Nice work @michaelkirk !

**Comment by michaelkirk** [comment]
> I didn't get to running the tests, but I assume all the tests are now passing. 

Yep, all the tests pass, though be aware of one peculiarity -

`cd jts-test-runner; cargo test` runs more JTS test cases than `cd geo; cargo test`

This is because the jts-test-runner/Cargo.toml is patched to point to your forked WKT which can parse more tests.

All the tests pass in either case, but something to be aware of.

**Comment by rmanoka** [comment]
I realize we don't yet test the `Contains` trait directly here (as it doesn't have all combinations implemented yet).   For now, I tried to manually match the `subject` and `target` in `Operation::Contains` like so:

``` rust
let verify_contains_trait = match (subject, target) {
    (Geometry::Point(subject), Geometry::Point(target)) => { subject.contains(target) == relate_actual }
    // ... all combinations that have contains implementation ...
    _ => { true }
};
```

Fortunately, it didn't trip any of the tests, so that's good.

**Comment by rmanoka** [comment]
@michaelkirk If it makes sense, you could merge [this PR](https://github.com/georust/jts-test-runner/pull/7) into this branch before merging to master.  It just manually checks the `Contains` implementation for the combinations where we have the trait implementation.  This is useful as we don't always use `Relate` in `impl Contains`. It might also come in handy to check which combinations are yet to be implemented.

**Comment by michaelkirk** [comment]
> This is useful as we don't always use Relate in impl Contains. It might also come in handy to check which combinations are yet to be implemented.

Good call. Done and thank you!

**Pull request merged**
