### PR TITLE
ci

### PR DESCRIPTION
**Pull request by michaelkirk**

### CODE REVIEW

**Comment by michaelkirk** [comment]
bors try

**Comment by michaelkirk** [comment]
PTAL @lnicola

**Comment by lnicola** [comment]
Looks good, but I'd skip `cargo-all-features`. It's not necessary right now (there are no optional features), and it's not sustainable when going over 3 or 4 optional features.

**Review by lnicola — APPROVED** [review]

**Comment by michaelkirk** [comment]
> I'd skip cargo-all-features. It's not necessary right now 

whooooops thanks @lnicola. I've fixed this.

bors r=lnicola

**Pull request merged**
